version: '3.5'

services:
  codenotary-be:
    build:
      context: ./codenotary-be/
      dockerfile: Dockerfile
    container_name: codenotary-be-service
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    volumes:
      - ./codenotary-be/src:/app/src
  codenotary-fe:
    build:
      context: ./codenotary-fe/
      dockerfile: Dockerfile
    container_name: codenotary-fe-service
    environment:
      - PORT=${PORT}
    depends_on:
      - codenotary-be
    ports:
      - '9000:9000'
    volumes:
      - ./codenotary-fe/src:/app/src
